
```{r}
measure_rules <- calculate_metric_measures %>%
  filter(
    .data$metric_measures_name %in%
      unique(metric_item[[level]]$metric_measures_name)
  ) %>%
  distinct()
if (nrow(measure_rules) != 1) {
  measure_rules %>%
    gt() %>%
    sub_missing(missing_text = "") %>%
    opt_table_font(size = 16) %>%
    tab_style(
      style = cell_text(weight = "bold"),
      locations = cells_column_labels(columns = everything())
    )
}
```

Calculation type: ``r measure_rules$metric_type`` (`r measure_rules$description_type`)

```{r results='asis'}
select_columns <- c("taxonname", "dutch_name", "taxoncode")
if (
  any(
    !is.na(measure_rules$values_column) &
      measure_rules$metric_type == "sum_values_column"
  )
) {
  select_columns <- c(select_columns, measure_rules$values_column)
}
if (any(!is.na(measure_rules$speciesfilter))) {
  taxonlist <- data_taxonmetrics %>%
    filter(eval(parse(text = (measure_rules$speciesfilter))))
}
if (is.na(measure_rules$speciesfilter) && length(select_columns) > 3) {
  taxonlist <- data_taxonmetrics
}
if (exists("taxonlist")) {
  cat("The species that are used for this calculation, are:\n\n")
  sal_present <- any("SAL.FAR." %in% taxonlist$taxoncode)
} else {
  cat("All observed fish species are used for this calculation.")
  sal_present <- TRUE
}
```

```{r }
if (exists("taxonlist")) {
  taxonlist %>%
    select(all_of(select_columns)) %>%
    gt() %>%
    sub_missing(missing_text = "") %>%
    opt_table_font(size = 16) %>%
    tab_style(
      style = cell_text(weight = "bold"),
      locations = cells_column_labels(columns = everything())
    )
}
if (exists("taxonlist")) {
  rm(taxonlist)
}
```

```{r results='asis'}
if (!is.na(measure_rules$exclude_species_length)) {
  cat(
    "Exception: individuals should be excluded from the calculation if they meet this rule:\n\n" # nolint: line_length_linter
  )
  cat(measure_rules$exclude_species_length)
  cat("\n\n")
}
if (
  !is.na(measure_rules$only_individual_measures) &&
    measure_rules$only_individual_measures == 1
) {
  cat("For this calculation, only individual measures should be used.\n\n")
}
if (!is.na(measure_rules$null_to_0)) {
  cat(
    "If the result of this calculation is `NULL`, it should be replaced by `0`.\n\n" # nolint: line_length_linter
  )
}
if (!is.na(measure_rules$saltru_to_salfar) && !measure_rules$saltru_to_salfar) {
  cat(
    "_Salmo trutta_ fario and _Salmo trutta_ trutta are treated as separate species/variants to calculate this metric; _Salmo trutta_ is treated as the same species as _Salmo trutta_ fario.\n\n" # nolint: line_length_linter
  )
} else {
  if (
    sal_present &&
      !measure_rules$metric_type %in% c("number_of_individuals", "total_weight")
  ) {
    cat(
      "_Salmo trutta_ fario, _Salmo trutta_ trutta and _Salmo trutta_ are treated as one species (and values of _Salmo trutta_ fario are used).\n\n" # nolint: line_length_linter
    )
  }
}
```

