
# `r index_information$english_name`

(Dutch: `r index_information$dutch_name`)

```{r echo=FALSE, results='asis'}
if (index_information$reference == "not published") {
  cat("This index is not published.")
  description_metrics_selection <- description_metrics %>%
    filter(is.na(publication))
} else if (startsWith(index_information$reference, "based on")) {
  cat("This index is ", index_information$reference, ".", sep = "")
  description_metrics_selection <- description_metrics %>%
    filter(
      publication ==
        gsub("(based on )?(.*)$", "\\2", index_information$reference)
    )
} else {
  cat("This index is published in ", index_information$reference, ".", sep = "")
  description_metrics_selection <- description_metrics %>%
    filter(publication == index_information$reference)
}
if (!is.na(index_information$add_info)) {
  cat(" ", index_information$add_info)
}
```


```{r echo=FALSE, include=FALSE, results='asis'}
output_indextypology <- NULL
metric_item <- list()
output_metric <- list()
formula <- list("")
metric_list <- indextypology_metric %>%
  filter(.data$indextypology == var_indextypology)
for (var_metric in metric_list$metric_name) {
  level <- 2
  metric_item[[level]] <- metric_list %>%
    filter(.data$metric_name == var_metric)
  output_indextypology <-
    c(output_indextypology, knit_child("_fiche_metric.Rmd"))
}
```

```{r results='asis'}
cat(output_indextypology, sep = "\n")
```
