
`r paste(paste0(rep("#", level), collapse = ""), var_metric)`

```{r include=FALSE, results='asis'}
output_metric[[level]] <- ""

description_metric <- description_metrics_selection %>%
  filter(metric == var_metric)
if (nrow(description_metric) == 0) {
  description_metric <- description_metrics_selection %>%
    filter(
      coalesce(
        metric == metric_item[[level]]$metric_measures_name,
        metric == metric_item[[level]]$metric_formula_name
      )
    )
}
if (nrow(description_metric) > 0) {
  output_metric[[level]] <- c(
    output_metric[[level]],
    paste0(
      paste0(
        "This metric represents the "[
          !(level == 2 && is.na(unique(metric_item[[level]]$metric_score_name)))
        ],
        unique(description_metric$description),
        ". "
      )[!is.na(unique(description_metric$description))],
      paste0(
        "It is named '",
        unique(description_metric$metric_in_publication),
        "' in ",
        unique(description_metric$publication),
        ".",
        sep = ""
      )[
        !is.na(unique(description_metric$metric_in_publication))
      ]
    )
  )
}

if (level == 2 && !is.na(metric_item[[2]]$method)) {
  method <- gsub("E", "electrofishing (E)", metric_item[[2]]$method)
  method <- gsub("SN", "trawling (SN)", method)
  method <- gsub("SF", "fykefishing (SF)", method)
  method <- gsub("\\|", ", ", method)
  output_metric[[level]] <- c(
    output_metric[[level]],
    sprintf(
      "_This metric should only be calculated from data collected by the method(s): %s._\n\n", # nolint: line_length_linter
      method
    )
  )
}
if (is.na(metric_item[[level]]$metric_measures_name)) {
  formula[[level]] <- calculate_metric_formula %>%
    filter(
      .data$metric_formula_name %in% metric_item[[level]]$metric_formula_name
    ) %>%
    mutate(
      submetric_name =
        ifelse(is.na(.data$submetric_formula_name),
               .data$submetric_measures_name, .data$submetric_formula_name)
    )
  output_metric[[level]] <- c(
    output_metric[[level]], sprintf("Formula to calculate __%s__:", var_metric)
  )
  output_metric[[level]] <- c(
    output_metric[[level]], paste0("__", unique(formula[[level]]$formula), "__")
  )
  output_metric[[level]] <- c(
    output_metric[[level]],
    "(The calculation of these variables is explained under the subtitles below.)" # nolint: line_length_linter
  )
  if (grepl("surface", unique(formula[[level]]$formula))) {
    output_metric[[level]] <- c(
      output_metric[[level]],
      paste(paste0(rep("#", level + 1), collapse = ""), "surface"),
      "surface expresses the effort of capturing:",
      "- for electrofishing: fished length (m) * fished river width (m)"[
        grepl("E", metric_item[[2]]$method)
      ],
      "- for fykefishing: n_fyke_nets ^ 2 * 40 (length in m) * 2 (width in m)"[
        grepl("SF", metric_item[[2]]$method)
      ],
      "- for trawling: fished length (m) * river width (m)"[
        grepl("SN", metric_item[[2]]$method)
      ]
    )
  }
  if (grepl("n_fyke_days", unique(formula[[level]]$formula))) {
    output_metric[[level]] <- c(
      output_metric[[level]],
      paste(paste0(rep("#", level + 1), collapse = ""), "n_fyke_days"),
      "'n_fyke_days' is the total number of days that fykes were used,
      so the number of fykes * the number of days."
    )
  }

  for (var_metric in unique(formula[[level]]$submetric_name)) {
    level <- level + 1
    metric_item[[level]] <- formula[[level - 1]] %>%
      filter(.data$submetric_name == var_metric) %>%
      transmute(
        metric_name = .data$submetric_name,
        metric_formula_name = .data$submetric_formula_name,
        metric_measures_name = .data$submetric_measures_name,
        metric_score_name = .data$submetric_score_name
      ) %>%
      distinct()
    output_metric[[level - 1]] <-
      c(output_metric[[level - 1]], knit_child("_fiche_metric.Rmd"))
    level <- level - 1
  }
}
if (is.na(metric_item[[level]]$metric_formula_name)) {
  output_metric[[level]] <-
    c(output_metric[[level]], knit_child("_fiche_metric_measure.Rmd"))
}
```

```{r include=FALSE, results='asis'}
if (!is.na(metric_item[[level]]$metric_score_name)) {
  var_metric_ms <-
    ifelse(is.na(metric_item[[level]]$metric_measures_name),
           metric_item[[level]]$metric_formula_name,
           metric_item[[level]]$metric_measures_name)
  var_metric_score <- metric_item[[level]]$metric_score_name
  output_metric[[level]] <-
    c(output_metric[[level]], knit_child("_fiche_metric_score.Rmd"))
}
```


```{r results='asis'}
cat(output_metric[[level]], sep = "\n\n")
```
